'use strict';
const $=s=>document.querySelector(s);
let skills=[],area=new URLSearchParams(location.search).get('area')||'Alle';
const isDetail=location.pathname.endsWith('/skill.html');
const symbols={Drive:'↗',Lead:'◎',Ship:'→',Yourself:'◌'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>s.toLocaleLowerCase('de').normalize('NFD').replace(/\p{Diacritic}/gu,'');
function render(){
 $('#areas').innerHTML=['Alle','Drive','Lead','Ship','Yourself'].map(a=>`<button data-area="${a}" aria-pressed="${a===area}">${a}<span>${skills.filter(s=>a==='Alle'||s.area===a).length}</span></button>`).join('');
 const q=normalize($('#search').value.trim());
 const found=skills.filter(s=>(area==='Alle'||s.area===area)&&(!$('#free-only').checked||s.free)&&normalize([s.title,s.desc,s.area,s.outcome].join(' ')).includes(q));
 $('#count').textContent=`${found.length} ${found.length===1?'Skill':'Skills'} entdecken`;
 $('#results').innerHTML=found.length?found.map(s=>`<a class="skill-row" href="skill.html?skill=${s.slug}" data-area="${s.area}"><span class="skill-symbol" aria-hidden="true">${symbols[s.area]}</span><span><strong>${esc(s.title)}</strong><small>${esc(s.desc)}</small></span><span class="area-label">${s.area}</span><span class="access-label ${s.free?'free':''}">${s.free?'Frei':'Leser'}</span><span class="row-arrow" aria-hidden="true">↗</span></a>`).join(''):'<div class="empty"><h3>Hier ist noch kein passender Skill.</h3><p>Probiere einen anderen Suchbegriff oder Bereich.</p><button class="button" id="reset">Filter zurücksetzen</button></div>';
}
function markdown(md){return md.replace(/^---\n[\s\S]*?\n---\n/,'').split(/\n\n/).map(b=>b.startsWith('# ')?'':b.startsWith('## ')?`<h3>${esc(b.slice(3))}</h3>`:`<p>${esc(b)}</p>`).join('');}
function detail(s){
 document.title=`${s.title} · KI-Skills · DRIVE Leadership`;
 $('#detail-content').innerHTML=`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="skills.html">KI-Skills</a><span aria-hidden="true">/</span><a href="skills.html?area=${s.area}">${s.area}</a><span aria-hidden="true">/</span><span aria-current="page">${esc(s.title)}</span></nav><header class="repo-heading"><div><p class="eyebrow">DRIVE / SKILL-BIBLIOTHEK</p><h1>${esc(s.title)}</h1><p>${esc(s.desc)}</p><div class="repo-tags"><a href="skills.html?area=${s.area}">${s.area}</a><span>${s.free?'Frei verfügbar':'Leserzugang'}</span><span>Beispielentwurf</span></div></div>${s.free?'<button class="button" id="download">↓ Skill herunterladen</button>':'<button class="button" data-access>Leserzugang ansehen ↗</button>'}</header><div class="repo-layout"><div class="repo-main"><section class="repo-start"><p class="eyebrow">MIT DEINER KI STARTEN</p><p>Lade die Datei herunter und gib sie deiner KI mit deinem Kontext. Zum Beispiel:</p><div class="starter-prompt"><span>Nutze den Skill „${esc(s.title)}“ und führe mich Schritt für Schritt durch die Methode.</span></div></section><section class="repo-file"><div class="repo-filebar"><span>▤ &nbsp; README.md</span><span>Über diesen Skill</span></div><div class="readme"><h2>${esc(s.title)}</h2><p>${esc(s.outcome)}</p><h3>Das bringst du mit</h3><p>${esc(s.context)}.</p><h3>So arbeitest du damit</h3><p>Starte mit deiner konkreten Führungssituation. Lass dir Fragen stellen, prüfe die Annahmen und entwickle den ersten Entwurf gemeinsam weiter. Nutze dazu das passende Kapitel im Buch.</p></div></section><section class="repo-file"><div class="repo-filebar"><span>▤ &nbsp; SKILL.md</span>${s.free?'<div class="view-tabs" role="group" aria-label="Ansicht"><button data-view="preview" aria-pressed="true">Vorschau</button><button data-view="source" aria-pressed="false">Quelltext</button></div>':'<span>Leser-Bibliothek</span>'}</div>${s.free?'<div id="md-view" class="markdown readme"></div>':'<div class="locked"><h3>Mit dem Buch geht es weiter.</h3><p>Die Beschreibung ist frei sichtbar. Der vollständige Skill soll nach Freischaltung verfügbar sein.</p><button class="copy" data-access>Zugangsoptionen ansehen ↗</button></div>'}</section></div><aside class="repo-sidebar"><h2>Über den Skill</h2><p>${esc(s.outcome)}</p><dl><dt>Bereich</dt><dd>${s.area}</dd><dt>Zugang</dt><dd>${s.free?'Frei ausprobieren':'Für Leser geplant'}</dd><dt>Format</dt><dd>Markdown · .md</dd><dt>Sprache</dt><dd>Deutsch</dd><dt>Stand</dt><dd>Inhaltlicher Entwurf</dd></dl>${s.free?'<button class="copy" id="copy">Markdown kopieren</button>':''}<p id="action-status" role="status"></p><div class="repo-aside-note"><h3>Dein Urteil bleibt entscheidend.</h3><p>Der Skill hilft beim Einstieg. Was für dein Team passt, entscheidest du.</p></div><a class="how-link" href="skills.html#how">Wie nutze ich einen Skill? ↗</a></aside></div>`;
 if(s.free){$('#md-view').innerHTML=markdown(s.md);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#md-view').className=b.dataset.view==='source'?'source readme':'markdown readme';if(b.dataset.view==='source')$('#md-view').textContent=s.md;else $('#md-view').innerHTML=markdown(s.md);});$('#download').onclick=()=>{const u=URL.createObjectURL(new Blob([s.md],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`${s.slug}-SKILL.md`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('#action-status').textContent='Download gestartet.';};$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(s.md);$('#action-status').textContent='Markdown kopiert.';}catch{$('#action-status').textContent='Bitte den Text im Tab SKILL.md manuell kopieren.';}};}

}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.area&&!b.dataset.skill){area=b.dataset.area;render();}if(b.dataset.skill)location.hash=b.dataset.skill;if(b.hasAttribute('data-access'))$('#access').showModal();if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.id==='reset'){area='Alle';$('#search').value='';$('#free-only').checked=false;render();}});
if(!isDetail){$('#search').addEventListener('input',render);$('#free-only').addEventListener('change',render);}
fetch('skills-data.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{skills=data;if(isDetail){const selected=skills.find(s=>s.slug===new URLSearchParams(location.search).get('skill'));if(selected)detail(selected);else $('#detail-content').innerHTML='<h1>Skill nicht gefunden</h1><p><a class="how-link" href="skills.html">Zurück zur Bibliothek →</a></p>';}else{if(!['Alle','Drive','Lead','Ship','Yourself'].includes(area))area='Alle';render();}}).catch(()=>{const el=isDetail?$('#detail-content'):$('#results');el.innerHTML='<p>Die Skills konnten nicht geladen werden. Bitte lade die Seite erneut.</p>';});
